## 张量的创建

In [57]:
import torch
import numpy as np

In [58]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

tensor([1, 2, 3])

In [59]:
torch.tensor(np.arange(15).reshape(3,5))

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]], dtype=torch.int32)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]], dtype=torch.int32)

In [60]:
torch.empty([3,4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [61]:
torch.ones([3,4])

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [62]:
torch.zeros([3,4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## 张量的属性和方法

In [63]:
a = torch.tensor([[[1]]])

In [64]:
a.item()

1

1

In [65]:
t = a.numpy()

In [66]:
type(t)

numpy.ndarray

numpy.ndarray

In [67]:
a.shape

torch.Size([1, 1, 1])

torch.Size([1, 1, 1])

In [68]:
a.size()

torch.Size([1, 1, 1])

torch.Size([1, 1, 1])

In [69]:
a = torch.tensor(np.arange(30).reshape(3,2,5))

In [70]:
a

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]], dtype=torch.int32)

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]], dtype=torch.int32)

In [71]:
a.size(1)

2

2

In [72]:
a.view([2,3,5])

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14]],

        [[15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]], dtype=torch.int32)

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14]],

        [[15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]], dtype=torch.int32)

In [73]:
b = torch.tensor(np.arange(15).reshape(3,5))

In [74]:
b

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]], dtype=torch.int32)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]], dtype=torch.int32)

In [75]:
b.transpose(0,1)  #直接交换行和列

tensor([[ 0,  5, 10],
        [ 1,  6, 11],
        [ 2,  7, 12],
        [ 3,  8, 13],
        [ 4,  9, 14]], dtype=torch.int32)

tensor([[ 0,  5, 10],
        [ 1,  6, 11],
        [ 2,  7, 12],
        [ 3,  8, 13],
        [ 4,  9, 14]], dtype=torch.int32)

In [76]:
b.view(5,-1) #把b展开之后等分为5分

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]], dtype=torch.int32)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]], dtype=torch.int32)

In [77]:
a  #[3,2,5]

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]], dtype=torch.int32)

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]], dtype=torch.int32)

In [78]:
a.transpose(0,1)  #[2,3,5]

tensor([[[ 0,  1,  2,  3,  4],
         [10, 11, 12, 13, 14],
         [20, 21, 22, 23, 24]],

        [[ 5,  6,  7,  8,  9],
         [15, 16, 17, 18, 19],
         [25, 26, 27, 28, 29]]], dtype=torch.int32)

tensor([[[ 0,  1,  2,  3,  4],
         [10, 11, 12, 13, 14],
         [20, 21, 22, 23, 24]],

        [[ 5,  6,  7,  8,  9],
         [15, 16, 17, 18, 19],
         [25, 26, 27, 28, 29]]], dtype=torch.int32)

In [79]:
b[1,:]

tensor([5, 6, 7, 8, 9], dtype=torch.int32)

tensor([5, 6, 7, 8, 9], dtype=torch.int32)

In [80]:
b[1]

tensor([5, 6, 7, 8, 9], dtype=torch.int32)

tensor([5, 6, 7, 8, 9], dtype=torch.int32)

In [81]:
b

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]], dtype=torch.int32)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]], dtype=torch.int32)

In [82]:
b[:,1]

tensor([ 1,  6, 11], dtype=torch.int32)

tensor([ 1,  6, 11], dtype=torch.int32)

In [83]:
b[:,1] = 100

In [84]:
b

tensor([[  0, 100,   2,   3,   4],
        [  5, 100,   7,   8,   9],
        [ 10, 100,  12,  13,  14]], dtype=torch.int32)

tensor([[  0, 100,   2,   3,   4],
        [  5, 100,   7,   8,   9],
        [ 10, 100,  12,  13,  14]], dtype=torch.int32)

In [85]:
b[-1,-1] = 100

In [86]:
b

tensor([[  0, 100,   2,   3,   4],
        [  5, 100,   7,   8,   9],
        [ 10, 100,  12,  13, 100]], dtype=torch.int32)

tensor([[  0, 100,   2,   3,   4],
        [  5, 100,   7,   8,   9],
        [ 10, 100,  12,  13, 100]], dtype=torch.int32)

In [87]:
b[-1,-1]

tensor(100, dtype=torch.int32)

tensor(100, dtype=torch.int32)

In [88]:
c = {100:10,20:10}

In [89]:
c[b.numpy()[-1,-1]]

10

10

In [90]:
b

tensor([[  0, 100,   2,   3,   4],
        [  5, 100,   7,   8,   9],
        [ 10, 100,  12,  13, 100]], dtype=torch.int32)

tensor([[  0, 100,   2,   3,   4],
        [  5, 100,   7,   8,   9],
        [ 10, 100,  12,  13, 100]], dtype=torch.int32)

In [91]:
b.max(dim=-1)[-1]

tensor([1, 1, 1])

tensor([1, 1, 1])

In [92]:
b

tensor([[  0, 100,   2,   3,   4],
        [  5, 100,   7,   8,   9],
        [ 10, 100,  12,  13, 100]], dtype=torch.int32)

tensor([[  0, 100,   2,   3,   4],
        [  5, 100,   7,   8,   9],
        [ 10, 100,  12,  13, 100]], dtype=torch.int32)

In [93]:
torch.FloatTensor([1,2,3]).dtype

torch.float32

torch.float32

In [94]:
a = torch.tensor([1,2,3])

In [95]:
torch.ones([2,3],dtype=torch.float32)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [96]:
b

tensor([[  0, 100,   2,   3,   4],
        [  5, 100,   7,   8,   9],
        [ 10, 100,  12,  13, 100]], dtype=torch.int32)

tensor([[  0, 100,   2,   3,   4],
        [  5, 100,   7,   8,   9],
        [ 10, 100,  12,  13, 100]], dtype=torch.int32)

In [97]:
b.new_ones(size=b.size())

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)

In [98]:
b.zero_()

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [99]:
b

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [100]:
b.add(1)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)

In [101]:
b.add_(1)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)

In [102]:
b

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)

## cuda类型的tensor

In [103]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu") 

In [104]:
device

device(type='cuda')

device(type='cuda')

In [105]:
a.device

device(type='cpu')

device(type='cpu')

In [106]:
a = a.to(device)

In [107]:
a

tensor([1, 2, 3], device='cuda:0')

tensor([1, 2, 3], device='cuda:0')

In [108]:
a.cpu().device

device(type='cpu')

device(type='cpu')

In [109]:
b = torch.tensor([0,0,0])

In [110]:
b

tensor([0, 0, 0])

tensor([0, 0, 0])

In [111]:
a+b.to(device)

tensor([1, 2, 3], device='cuda:0')

tensor([1, 2, 3], device='cuda:0')

In [112]:
a.cpu().numpy()

array([1, 2, 3], dtype=int64)

array([1, 2, 3], dtype=int64)