In [1]:
import torch
import numpy as np
from torchvision.transforms import ToTensor

e:\Anaconda\envs\PT1.7\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
t = torch.tensor(np.arange(24).reshape(2,4,3)) #[h,w,c]

In [3]:
t

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]], dtype=torch.int32)

In [4]:
#[h,w,c] ---> [c,h,w]

In [5]:
t.transpose(0,2).transpose(1,2)

tensor([[[ 0,  3,  6,  9],
         [12, 15, 18, 21]],

        [[ 1,  4,  7, 10],
         [13, 16, 19, 22]],

        [[ 2,  5,  8, 11],
         [14, 17, 20, 23]]], dtype=torch.int32)

In [6]:
t.permute(2,0,1)  #[0,1,2] ---> [2,0,1]

tensor([[[ 0,  3,  6,  9],
         [12, 15, 18, 21]],

        [[ 1,  4,  7, 10],
         [13, 16, 19, 22]],

        [[ 2,  5,  8, 11],
         [14, 17, 20, 23]]], dtype=torch.int32)

In [7]:
ToTensor()(t.numpy())

tensor([[[ 0,  3,  6,  9],
         [12, 15, 18, 21]],

        [[ 1,  4,  7, 10],
         [13, 16, 19, 22]],

        [[ 2,  5,  8, 11],
         [14, 17, 20, 23]]], dtype=torch.int32)

In [8]:
from tqdm import tqdm
import time

In [9]:
for i in tqdm(range(100),ascii=True,total=100,desc="Output"):
#     print(i)
    time.sleep(0.5)
    pass

Output: 100%|##########| 100/100 [00:51<00:00,  1.95it/s]


In [10]:
a = t[0,0,:]

In [11]:
b = t[0,1,:]

In [12]:
a

tensor([0, 1, 2], dtype=torch.int32)

In [13]:
a.eq(b).float().mean()

tensor(0.)