In [1]:
import torch
import numpy as np

e:\Anaconda\envs\PT1.7\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


## Forward calculation

In [2]:
x = torch.ones([2,2],requires_grad=True)

In [3]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [4]:
y = x+2

In [5]:
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [6]:
z = 3*y.pow(2)

In [7]:
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [8]:
out = z.mean()

In [9]:
out

tensor(27., grad_fn=<MeanBackward0>)

## Backward propagation

In [10]:
out.backward(retain_graph=True)

In [11]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [12]:
out.backward(retain_graph=True)

In [13]:
x.grad

tensor([[9., 9.],
        [9., 9.]])

## Be careful

In [14]:
t = torch.tensor(np.arange(12).reshape(3,4))

In [15]:
t

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]], dtype=torch.int32)

In [16]:
t.data

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]], dtype=torch.int32)

In [17]:
t.data[-1,-1] = 100

In [18]:
t

tensor([[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10, 100]], dtype=torch.int32)

In [19]:
out.data

tensor(27.)

In [20]:
out

tensor(27., grad_fn=<MeanBackward0>)

In [21]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [22]:
x.data[-1,-1] = 100

In [23]:
x.data.numpy()

array([[  1.,   1.],
       [  1., 100.]], dtype=float32)

In [24]:
x

tensor([[  1.,   1.],
        [  1., 100.]], requires_grad=True)

In [25]:
a = torch.tensor(x).clone()

e:\Anaconda\envs\PT1.7\lib\site-packages\ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.


In [26]:
a[-1,-1] = 10

In [27]:
a

tensor([[ 1.,  1.],
        [ 1., 10.]])

In [28]:
x

tensor([[  1.,   1.],
        [  1., 100.]], requires_grad=True)

# test

In [29]:
a = torch.rand([1])

In [30]:
a

tensor([0.1426])

In [31]:
a.zero_()

tensor([0.])

In [32]:
a

tensor([0.])

In [33]:
w = torch.rand([],requires_grad=True)


In [34]:
print(w.grad)

None
